name: just_one_ten_mins

dependencies:
  flutter:
    sdk: flutter
  # 상태 관리
  flutter_riverpod: ^2.4.9
  # 라우팅
  auto_route: ^7.8.4
  # 의존성 주입
  get_it: ^7.6.7
  # 불변 객체
  freezed_annotation: ^2.4.1
  
  # PDF 처리
  file_picker: ^6.1.1
  pdf_text: ^0.5.0
  
  # 오디오 관련
  just_audio: ^0.9.36
  flutter_tts: ^3.8.5
  
  # 저장소
  isar: ^3.1.0
  path_provider: ^2.1.2
  
  # 네트워크
  dio: ^5.4.0
  
dev_dependencies:
  # 코드 생성기
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  freezed: ^2.4.6
  isar_generator: ^3.1.0 

environment:
  sdk: '>=3.1.5 <4.0.0'